tables:
  ingest:
    analyst:
      - select
    ingestion:
      - select
      - operate
      - ownership
    developer:
      - select
      - operate
    sysadmin:
      - select
      - operate

  integrate:
    analyst:
      - select
      - operate
    developer:
      - select
      - operate
    sysadmin:
      - select
      - operate
      - ownership

  clean:
    analyst:
      - select
    developer:
      - select
      - operate
    sysadmin:
      - select
      - operate
      - ownership

  normalize:
    analyst:
      - select
    developer:
      - select
      - operate
      - truncate
    sysadmin:
      - select
      - operate
      - ownership

  analyze:
    analyst:
      - select
    developer:
      - select
      - operate
    sysadmin:
      - select
      - operate
      - ownership