schemas:
  ingest:
    analyst:
      - usage
    ingestion:
      - usage
      - create table
      - create view
      - create function
      - create procedure
      - create stream
      - create task
      - create stage
    developer:
      - usage
      - create table
      - create view
      - create function
      - create procedure
      - create stream
      - create task
      - create stage
    sysadmin:
      - usage
      - create table
      - create view
      - create function
      - create procedure
      - create stream
      - create task
      - create stage

  integrate:
    analyst:
      - usage
    developer:
      - usage
      - create table
      - create view
      - create function
      - create procedure
      - create stream
      - create task
      - create stage
    sysadmin:
      - usage
      - create table
      - create view
      - create function
      - create procedure
      - create stream
      - create task
      - create stage

  clean:
    analyst:
      - usage
    developer:
      - usage
      - create table
      - create view
      - create function
      - create procedure
      - create stream
      - create task
      - create stage
    sysadmin:
      - usage
      - create table
      - create view
      - create function
      - create procedure
      - create stream
      - create task
      - create stage

  normalize:
    analyst:
      - usage
    developer:
      - usage
      - create table
      - create view
      - create function
      - create procedure
      - create stream
      - create task
      - create stage
    sysadmin:
      - usage
      - create table
      - create view
      - create function
      - create procedure
      - create stream
      - create task
      - create stage

  analyze:
    analyst:
      - usage
    developer:
      - usage
      - create table
      - create view
      - create function
      - create procedure
      - create stream
      - create task
      - create stage
    sysadmin:
      - usage
      - create table
      - create view
      - create function
      - create procedure
      - create stream
      - create task
      - create stage