tables:
  ingest:
    analyst:
      - select
    ingestion:
      - select
      - insert
      - update
      - delete
      - truncate

    developer:
      - select
      - insert
      - update
      - delete
      - truncate
    sysadmin:
      - select
      - insert
      - update
      - delete
      - truncate

  integrate:
    analyst:
      - select
    developer:
      - select
      - insert
      - update
      - delete
      - truncate
    sysadmin:
      - select
      - insert
      - update
      - delete
      - truncate

  clean:
    analyst:
      - select
    developer:
      - select
      - insert
      - update
      - delete
      - truncate
    sysadmin:
      - select
      - insert
      - update
      - delete
      - truncate

  normalize:
    analyst:
      - select
    developer:
      - select
      - insert
      - update
      - delete
      - truncate
    sysadmin:
      - select
      - insert
      - update
      - delete
      - truncate

  analyze:
    analyst:
      - select
    developer:
      - select
      - insert
      - update
      - delete
      - truncate
    sysadmin:
      - select
      - insert
      - update
      - delete
      - truncate