views:
  ingest:
    analyst:
      - select
      - references
    ingestion:
      - select
      - references
    developer:
      - select
      - references
    sysadmin:
      - select
      - references

  integrate:
    analyst:
      - select
      - references
    developer:
      - select
      - references
    sysadmin:
      - select
      - references

  clean:
    analyst:
      - select
      - references
    developer:
      - select
      - references
    sysadmin:
      - select
      - references

  normalize:
    analyst:
      - select
      - references
    developer:
      - select
      - references
    sysadmin:
      - select
      - references

  analyze:
    analyst:
      - select
      - references
    developer:
      - select
      - references
    sysadmin:
      - select
      - references