schemas:
  ingest:
    analyst:
      - select
      - references
    ingestion:
      - select
      - references
      - ownership
    developer:
      - select
      - references
    sysadmin:
      - select
      - references

  integrate:
    analyst:
      - select
      - references
    developer:
      - select
      - references
    sysadmin:
      - select
      - references
      - ownership

  clean:
    analyst:
      - select
      - references
    developer:
      - select
      - references
    sysadmin:
      - select
      - references
      - ownership

  normalize:
    analyst:
      - select
      - references
    developer:
      - select
      - references
    sysadmin:
      - select
      - references
      - ownership

  analyze:
    analyst:
      - select
      - references
    developer:
      - select
      - references
    sysadmin:
      - select
      - references
      - ownership