databases:
  raw: 
    roles:
      - r
      - rw
  prepare:
    roles:
      - r
      - rw
  normalize:
    roles:
      - r
      - rw
  integrate:
    roles:
      - r
      - rw
  analyze:
    roles:
      - r
      - rw