tables:
  raw:
    analyst:
      - select
    ingestion:
      - select
      - operate
      - ownership
    developer:
      - select
      - operate
    sysadmin:
      - select
      - operate

  prepare:
    analyst:
      - select
      - operate
    developer:
      - select
      - operate
    sysadmin:
      - select
      - operate
      - ownership

  normalize:
    analyst:
      - select
    developer:
      - select
      - operate
    sysadmin:
      - select
      - operate
      - ownership

  integrate:
    analyst:
      - select
    developer:
      - select
      - operate
    sysadmin:
      - select
      - operate
      - ownership

  analyze:
    analyst:
      - select
    developer:
      - select
      - operate
    sysadmin:
      - select
      - operate
      - ownership