schemas:
  ingest:
    analyst:
      - usage
    ingestion:
      - usage
      - create table
      - create view
      - create function
      - create procedure
      - create stream
      - create task
      - create stage
      - create dynamic table
      - ownership
    developer:
      - usage
      - create table
      - create view
      - create function
      - create procedure
      - create stream
      - create task
      - create stage
      - create dynamic table
    sysadmin:
      - usage
      - create table
      - create view
      - create function
      - create procedure
      - create stream
      - create task
      - create stage

  integrate:
    analyst:
      - usage
    developer:
      - usage
      - create table
      - create view
      - create function
      - create procedure
      - create stream
      - create task
      - create stage
      - create dynamic table
    sysadmin:
      - usage
      - create table
      - create view
      - create function
      - create procedure
      - create stream
      - create task
      - create stage
      - ownership
      - create dynamic table

  clean:
    analyst:
      - usage
    developer:
      - usage
      - create table
      - create view
      - create function
      - create procedure
      - create stream
      - create task
      - create stage
      - create dynamic table
    sysadmin:
      - usage
      - create table
      - create view
      - create function
      - create procedure
      - create stream
      - create task
      - create stage
      - create dynamic table
      - ownership
      
  normalize:
    analyst:
      - usage
    developer:
      - usage
      - create table
      - create view
      - create function
      - create procedure
      - create stream
      - create task
      - create stage
    sysadmin:
      - usage
      - create table
      - create view
      - create function
      - create procedure
      - create stream
      - create task
      - create stage
      - create dynamic table
      - ownership

  analyze:
    analyst:
      - usage
    developer:
      - usage
      - create table
      - create view
      - create function
      - create procedure
      - create stream
      - create task
      - create stage
      - create dynamic table
    sysadmin:
      - usage
      - create table
      - create view
      - create function
      - create procedure
      - create stream
      - create task
      - create stage
      - create dynamic table
      - ownership