users:
  dbt:
    roles:
      - transform
    warehouse: transform
    type: service
  fivetran:
    roles:
      - ingestion
    warehouse: ingestion
    type: legacy_service
  reporting:
    roles:
      - analyst
    warehouse: reporting
