users:
  dbt:
    role: transform
    warehouse: transform
    type: service
  fivetran:
    role: ingestion
    warehouse: ingestion
    type: legacy_service
  reporting:
    role: analyst
    warehouse: reporting
  trajche:
    role: transformer
    warehouse: transformer
    existing: true
