warehouses:
  ingestion:
    auto_suspend: 60
    roles:
      ingestion: 
        - usage
        - operate
      monitoring:
        - monitor
  developer:
    roles:
      developer:
        - usage
        - operate
      monitoring:
        - monitor
  reporting:
    roles:
      analyst: 
        - usage
        - operate
      monitoring:
        - monitor
  monitoring:
    auto_suspend: 60
    roles:
      monitoring:
        - usage
        - monitor
        - operate