warehouses:
  ingest:
    monitoring:
      - monitor
    ingestion: 
      - usage
      - operate

  developer:
    developer:
      - usage
      - operate
    monitoring:
      - monitor

  reporting:
    analyst: 
      - usage
      - operate
    monitoring:
      - monitor

  monitoring:
    monitoring:
      - usage
      - monitor
      - operate