name: Plan Snowflake Infrastructure (Auto)
on:
  pull_request:
    branches:
      - main
jobs:
  ci-infrastructure:
    name: 'Dev'
    uses: ./.github/workflows/plan.yaml
    environment: development
    permissions:
      id-token: write # required to use OIDC authentication
      contents: read # required to checkout the code from the repo
    with:
      targetEnvironment: development
      alwaysApplyGrants: false
      logDebug: OFF
    secrets: inherit