name: Deploy Snowflake Infra
on:
  workflow_dispatch:
    inputs:
      targetEnvironment:
        type: choice
        description: Deploy to
        options: 
        - development
        - production
        required: true
        default: 'development'
      logDebug:
        type: choice
        description: TF_LOG debug level
        options:
        - TRACE
        - 'OFF'
        required: true
        default: 'OFF'

jobs:
  Deploy:
    name: Deploy Terraform
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.targetEnvironment }}
    defaults:
      run:
        shell: bash
        working-directory: terraform/02-snowflake-infrastructure
    concurrency: infra-deploy

    steps:
    - uses: actions/checkout@v3

    - name: Set terraform environment variables
      run: |
        # ALL ENVS
        echo "TF_LOG=${{ github.event.inputs.logDebug }}" >> $GITHUB_ENV
        echo "BACKEND_ENCRYPT=true" >> $GITHUB_ENV
        echo "ENVIRONMENT=${{ github.event.inputs.targetEnvironment }}" >> $GITHUB_ENV
        echo "SNOWFLAKE_PRIVATE_KEY<<EOF" >> $GITHUB_ENV
        echo "${{ secrets.SNOWFLAKE_PRIVATE_KEY }}" >> $GITHUB_ENV
        echo "EOF" >> $GITHUB_ENV

        # PER ENV
        case "${{ github.event.inputs.targetEnvironment }}" in
          "development")
            echo "TF_VAR_aws_role_arn=arn:aws:iam::123456789123:role/cfl-GitHubActions" >> $GITHUB_ENV
          ;;
          "production")
            echo "TF_VAR_aws_role_arn=arn:aws:iam::123456789123:role/cfl-GitHubActions" >> $GITHUB_ENV
          ;;
          *)
            echo "Missed something"
          ;;
        esac

    - name: install terraform
      uses: hashicorp/setup-terraform@v1.2.1
      with:
        terraform_version: 1.2.4
        terraform_wrapper: false

    - name: Debug info
      if: github.event.inputs.logDebug == 'TRACE'
      run: |
        env
        git config --list
        pwd
        ls -la

    - name: Initialize Terraform
      run: |
        terraform init -backend-config="backend-$ENVIRONMENT.tfvars"

    - name: Format terraform
      run: terraform fmt -check

    - name: Validate terraform
      run: terraform validate

    - name: Plan terraform
      run: |
        terraform plan --var-file=$ENVIRONMENT.tfvars -out=./output.tfplan

    # Publish output
    - name: Publish artifact
      uses: actions/upload-artifact@v2
      with:
        name: terraform-plan-file
        path: terraform/02-snowflake-infrastructure/output.tfplan

    - name: Apply terraform
      run: |
        terraform apply -auto-approve ./output.tfplan

