name: Plan Infrastructure on PR
on:
  pull_request:
    types: [opened, reopened]

jobs:
  ci-infrastructure:
    name: 'Dev'
    concurrency: ci-infrastructure
    uses: ./.github/workflows/infra-plan-manual.yaml
    with:
      targetEnvironment: development
      alwaysApplyGrants: false
      logDebug: OFF
    secrets: inherit