name: Plan Infrastructure on PR
on:
  pull_request_target:
    branches: [ "main" ]

jobs:
  ci-infrastructure:
    name: 'Dev'
    concurrency: ci-infrastructure
    uses: ./.github/workflows/infra-plan-manual.yaml
    permissions:
      id-token: write
      contents: read
    with:
      targetEnvironment: development
      alwaysApplyGrants: false
      logDebug: OFF
    secrets: inherit
